{{- if .Values.managedServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "ph-ee-identity-account-mapper"
  annotations:
    {{- with .Values.serviceAccountAnnotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  labels:
    app: "ph-ee-identity-account-mapper"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  {{- end -}}